### ISSUE TITLE
Visual glitch with large balance amounts, long name address and medium screens

### ISSUE THREAD

**Issue by Albermonte** [nimiq/wallet#102]
There's a visual glitch when a wallet has more than 1 address and that address has a large amount of NIM.

As you can see the rigth padding is not working
<details>
  <summary>Full page</summary>
  
![image](https://user-images.githubusercontent.com/14013679/157739815-33fc4da1-1a2b-47b2-b1c6-015d1b2b1941.png)

</details>

![image](https://user-images.githubusercontent.com/14013679/157739131-f0df4842-b5c2-4c16-a23d-6284143ce7a0.png)

And the glitch is even worst if the amounts are hidden
![image](https://user-images.githubusercontent.com/14013679/157739252-d1dc7019-91c4-4092-bf51-4f48412e2a8b.png)

This does not happen if the amounts are first hidden and then switched to the second address
![image](https://user-images.githubusercontent.com/14013679/157739401-17f14668-e631-43a1-8a49-d1d87352efc6.png)

Also not happening on the first address (due to the "short" name)
![image](https://user-images.githubusercontent.com/14013679/157740315-5a1ea9d4-5b98-4090-a14a-f1b8ab7508c3.png)

Neither on the third one (due to the "short" name)
![image](https://user-images.githubusercontent.com/14013679/157740563-25ce1fa6-b0bc-4601-9aff-bdfcb4d66c83.png)

The body width is `941px`

**Comment by mraveux** [comment]
Hi! 👋 
Thank you for the detailed report and screenshots, allowed me to quickly find a solution!
(btw your body width is actually `1186px` , `941px` was the height 😉)

The commit #104 should fix the issue and will be deployed with the next wallet update.

Thanks for the contribution! Let us know if the issue persist in the future (once the update is deployed).
