### ISSUE TITLE
Can't swap crypto to fiat in Portuguese bank 

### ISSUE THREAD

**Issue by ilyaLibin** [nimiq/wallet#105]
**Facts:**
The selling crypto is supported with every bank in EU. SEPA allows faster transactions however it's not required as the modal suggests.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/12880486/158014589-e406b846-9d24-46cc-a398-2fdd97dbc5e6.png">

```
Without a SEPA instant bank account, your money will take 1-3 business days to arrive.
```

**Issue**
The validation of the form blocks users to select not a SEPA bank for selling flow.
1) When trying to find my bank:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/12880486/158014697-f48dc584-6b24-4116-8708-6732e8a1e917.png">

2) When choosing different bank from the list:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/12880486/158014665-cdee00b6-03a8-466a-b5ef-ece9181e48e7.png">

**Expected/suggested behavior**
Allow users to use any supported bank (SEPA/not SEPA) and only have a tag on the side that indicates that the bank has SEPA support.

**Comment by sisou** [comment]
We are currently investigating how to best handle this case in the Wallet. In the meantime, you can already use https://supersimpleswap.com by Nimiq, to swap crypto-to-EUR with any IBAN.

**Comment by ilyaLibin** [comment]
> We are currently investigating how to best handle this case in the Wallet. In the meantime, you can already use https://supersimpleswap.com by Nimiq, to swap crypto-to-EUR with any IBAN.

Thank you, @sisou ! 
I tried using that tool, but there is one confusing thing that I'm not sure I understand completely.. 
In super simple swap, what’s a fee per byte? How should I calculate the final transaction amount?
Let’s say I want to convert 0.001 bitcoin to eur, and the fee per byte is  10 satoshi. How much should I send to the address?

Also because of timeout, I'm banned and my maximum amount is reduced to 0 🤦

**Comment by sisou** [comment]
The amount that needs to arrive at the swap address in your example is 0.001 BTC, which is the amount you set as the transaction value in your wallet. You need to pay an _additional_ fee of 10 sat/byte (in this example). In your wallet, you should be able to set this fee. In case of the Nimiq Wallet, when sending BTC you can select the fee at the bottom of the sending dialog, the tooltip tells you the fee/byte for the selected setting.
![image](https://user-images.githubusercontent.com/1828163/160621477-61ad821c-be0a-4d3c-a924-84d5aa70a130.png)

Are you using another wallet for BTC?
