### ISSUE TITLE
Settings on iOS

### ISSUE THREAD

**Issue by felix-schindler** [nimiq/wallet#106]
On iPhone Safari (v15.3) the settings are in a row instead of a column. It's not possible to scroll horizontally to reach other options. 

This is not reproducible in any Browser with "Responsive Design"-Mode.

<details>
    <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/65357346/158050563-141b8a8b-d51f-4704-bc25-eae1a2e05779.PNG" alt="Screenshot of the Bug">
</details>

https://github.com/nimiq/wallet/blob/6786330d894da24142402b4819490717b47c893d/src/components/layouts/Settings.vue#L11

**Comment by sisou** [comment]
Thank you Felix, the next update will include a fix for this!

**Comment by sisou** [comment]
Released now in v2.29.0 :tada:
