### ISSUE TITLE
404 for static files

### ISSUE THREAD

**Issue by felix-schindler** [nimiq/wallet#121]
<img width="501" alt="screenshot-1" src="https://user-images.githubusercontent.com/65357346/203944143-634442ff-606c-4827-9f4d-b2bad41da94e.png">
<img width="499" alt="screenshot-2" src="https://user-images.githubusercontent.com/65357346/203944150-077c3650-1a03-4ada-9660-2ef07497d487.png">

**Comment by sisou** [comment]
Thank you! Investigating...

**Comment by sisou** [comment]
Fixed, please try again! 👍
