### ISSUE TITLE
Refactoring request: Multiple cryptocurrencies

### ISSUE THREAD

**Issue by Saiv46** [nimiq/wallet#126]
When Wallet will support Etherium beside Bitcoin, address panel will start looking cluttered (especially on mobile).

Possible solution:
Turn Bitcoin account container into container with logos of supported cryptocurrencies labeled "Other cryptocurrencies". On click everything will slide bottom-up, hiding addresses and revealing supported cryptocurrencies (looking like addresses), while container will fade into "Main account" with back 🔙 icon. Clicking again will do the reverse. Mobile gestures can work with that too.

**Comment by julianbauer** [comment]
@Saiv46 thanks for this suggestion, it's an interesting approach, I can picture the animations. And I absolutely agree that with more currencies it would start to get cluttered. We're actually working on redesigning this part of the wallet right now, stay tuned :)

**Comment by sisou** [comment]
Solved with side-by-side layout for BTC and USDC/T a while ago.
