### ISSUE TITLE
Don't show negative block value number

### ISSUE THREAD

**Issue by DovAzencot** [nimiq/wallet#150]
Place a loader or a skeleton until the wallet is sync with network height in order not to show negative value.

<img width="665" alt="Screenshot 2024-03-11 at 4 51 20" src="https://github.com/nimiq/wallet/assets/64713477/f10f684d-9ec9-4728-8808-77ded4c1bb1a">

**Comment by sisou** [comment]
Fixed by 3a5033551a398a76cca47797bffa6b783e4c1337.
