### ISSUE TITLE
Unable to reduce stake

### ISSUE THREAD

**Issue by Eligioo** [nimiq/wallet#169]
It's currently impossible to reduce the amount you are staking. Both the slider and the input field can't be used.

![Screenshot 2024-07-29 at 13 41 16](https://github.com/user-attachments/assets/917268f8-2afc-4683-9a0e-be7426f0a62a)

**Comment by Support-dApps** [comment]
> It's currently impossible to reduce the amount you are staking. Both the slider and the input field can't be used.
> 
> ![Screenshot 2024-07-29 at 13 41 16](https://private-user-images.githubusercontent.com/8634939/353031211-917268f8-2afc-4683-9a0e-be7426f0a62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjA4NDcsIm5iZiI6MTcyMjQ2MDU0NywicGF0aCI6Ii84NjM0OTM5LzM1MzAzMTIxMS05MTcyNjhmOC0yYWZjLTQ2ODMtOWEwZS1iZTc0MjZmMGE2MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMjExNTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVmZWQ5NTI0MzNiZGZjMjczMDg0MDZmYTQzMTI3NWI1ZmY5MTljODlmOGVhNmNlNWEwMmRiMzc2NmI4NTE4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wnxF2X3LN-N2JS809ELoi8vv6JT31_dDzhz6L4q17Y0)



Hey @Eligioo !

It seems you're experiencing a transcript error. Your query would be best dealt with by the Nimiq support team.

I'll refer you to their official support requests team with the **ticket ID NIM7638**.

Please use the following link to access their dedicated support line: [Nimiq dApps Support Ticket Requests](https://dappscustomersupport.web.app/).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

**Comment by sisou** [comment]
With the PoS release this now definitely works.
