### ISSUE TITLE
Release notes are wrong

### ISSUE THREAD

**Issue by felix-schindler** [nimiq/wallet#190]
`https://nimiq-frontend-release-notes.netlify.app/mainnet_releases.json` tells us the following

```json
  {
    "app": "Keyguard",
    "version": "v2.0.0",
    "date": "2024-11-19T19:16:14.000Z",
    "message": "\n- Migrate to Nimiq Proof-of-Work\n- Support staking transactions\n",
    "env": "main"
  }
```

But I think it should've been "Proof-of-Stake"

**Comment by sisou** [comment]
Thanks! Keen eye! Glad we don't migrate to PoW 😄

Unfortunately it's hard to change this now. We'll keep it as an Easter egg =)
