### ISSUE TITLE
Deactivating stake multiple times

### ISSUE THREAD

**Issue by onmax** [nimiq/wallet#193]
I can deactivate my stake multiple times. 

This might be confusing for the user that does not know that he will receive the stake once epoch finishes

**Comment by sisou** [comment]
Is this still relevant?

I fixed the bug yesterday where the "unstake" button was falsely enabled even when stake was not unstakable.

**Comment by onmax** [comment]
![Image](https://github.com/user-attachments/assets/d9e5145a-f39f-48fe-80b1-9bbcce8bbeba)
