### ISSUE TITLE
Cashlink can't be activated, and it does not show generated link unless page is refreshed

### ISSUE THREAD

**Issue by iSQL** [nimiq/wallet#195]
Cashlink feature does not work.

1. Creating cashlink window "Creating your cashlink" loads indefinately, and does not show cashlink url unless window is refreshed. 

- When refreshed, it properly shows cashlink url.

2. When 2nd person wants to open a wallet thru this cashlink url, it just loads, refresh does not help.

- I tried on 2 phones and 2 browsers, every case behaved in the same way.

**Comment by sisou** [comment]
Fixed in nimiq/hub@25c14662938d326f3f420d372e8b5f976a840192 and released as v2.0.4.
