### ISSUE TITLE
Adding parameters for custom transactions

### ISSUE THREAD

**Issue by rraallvv** [nimiq/wallet#2]
As much as I'd like to have a way to integrate Nimiq payments into native and web applications, a better solution would be for those application to have a way to pass the information needed for each transaction right into the parameters passed to the browser-based wallet. Since most operative systems have a way to associate a certain domain or protocol with an app, the users will have also the option to use the digital wallet they preffer. This would allow users to make the transaction from a familiar interface and an application they already trust. They even could check that the amount is the one specified in the application that want them to make the payment. In turn the application could pass some custom data for extended transactions, with some information associated with the payment.

**Comment by Bettelstab** [comment]
Sorry for answering so late. We are working on such a setup which you described. https://github.com/nimiq/accounts will be one possible entry point then.
