### ISSUE TITLE
StakingInfoPage: Show ShortAddress for custom validators

### ISSUE THREAD

**Issue by mraveux** [nimiq/wallet#200]
Currently, when staking with an unregistered validator or before the Validator API request, in the title of the StakingInfoPage the full validator address is displayed instead of the short version.

**Comment by Elsonbastey** [comment]
> Currently, when staking with an unregisteres validator or before the Validator API request, in the title of the StakingInfoPage the full validator address is displayed instead of the short version.


Hello @mraveux 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID STK07638
Please see the link below to our dedicated support line:
[DApps Node Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
