### ISSUE TITLE
Put pool self description in “…”

### ISSUE THREAD

**Issue by Tammoovernice** [nimiq/wallet#212]
![Image](https://github.com/user-attachments/assets/e17f63c8-a678-482c-a60d-d86f2b82fce7)

**Comment by sisou** [comment]
I don't understand what you mean @Tammoovernice. Where is `"..."`? 

@mraveux Do you understand this?

**Comment by sisou** [comment]
I experimented with a lot of different designs for the quotes. Big opaque quotes, different alignments. But nothing looked very nice. If you want, you can look at a nice design that features the opening quote more prominently as a design element.

For now, this is using the `<q>` HTML element which will use quotes appropriate for the user's browser locale.
![Image](https://github.com/user-attachments/assets/65b30b39-5da2-469b-8d01-d8b33a2483b6)
