### ISSUE TITLE
Copy commenting the score sometimes missing

### ISSUE THREAD

**Issue by Tammoovernice** [nimiq/wallet#213]
![Image](https://github.com/user-attachments/assets/236de128-ae0b-4a3d-8a11-1bdcddcbb2e6)

Check https://www.figma.com/design/Ibvnl8VXJiRYDdMAShmjNt/Staking-feature?node-id=6846-41276&t=3vomW63gfX92MZGb-1

**Comment by sisou** [comment]
According to the code, this cannot happen... :/

**Comment by sisou** [comment]
Please re-open when you still experience this after the next wallet release.
