### ISSUE TITLE
Delay “Stake must be at least 100 NIM.” note so it not always shows when moving the slider

### ISSUE THREAD

**Issue by Tammoovernice** [nimiq/wallet#214]
https://github.com/user-attachments/assets/f06d757f-237e-4030-8e6a-08aa56f9e2ef

**Comment by sisou** [comment]
This should not have happened anymore since Wednesday evening (a368891ead667daa629b348df3b9e6e5edc54d4e), as the slider can now no longer be moved into the 0-100 NIM section.
