### ISSUE TITLE
If validator is not a pool, show a message

### ISSUE THREAD

**Issue by Albermonte** [nimiq/wallet#226]
If `payoutType` is `none` show a mesage telling the user that this validator is not going to pay them any reward to prevent misunderstandings

```
    "id": 47,
    "name": "Private Whalidator",
    "address": "NQ60 GH2T VEA2 CUR5 SXAD QU9B 7ELD YMG5 5T7U",
    "fee": null,
    "payoutType": "none",
```

**Comment by sisou** [comment]
Validators that are named but are not a pool are hidden now (with the next deployment): 9ad92665c4a75aca0093da96ba99be0b29193893
