### ISSUE TITLE
Replace identicon of staking contract with staking icon

### ISSUE THREAD

**Issue by sisou** [nimiq/wallet#239]
See Figma for the icon, replace everywhere.

Either as a `v-if` wherever we show an identicon, or as a wrapper around the `Identicon` component, or pull the Identicon component into the wallet src.

**Comment by mraveux** [comment]
I pushed 2 commits regarding this issue. Is there other places I should change it other than the TransactionListItem and the TransactionModal @sisou?

**Comment by sisou** [comment]
I think not. When interacting with it, no identicon is shown, and in the Keyguard we show the validator/pool icon instead.

So should be good!

**Comment by mraveux** [comment]
Perfect 👏

edit: I will still sync with the designers to be sure we have something that match what they expect.
