### ISSUE TITLE
Support old requestLink generated from the donation app / safe

### ISSUE THREAD

**Issue by mraveux** [nimiq/wallet#24]
Currently the wallet doesn't support the old requestLink format used in the safe & in the donation app.
The donation app will be updated to generate new requestLink for the wallet, but we should still support old ones.

**Comment by mariofriz** [comment]
@Yukiioz Could you please confirm if I understand this correctly.
Considering this old safe request link: `https://safe.nimiq.com/#_request/NQ208P9L3YMDGQYT1TAA8D0GMC125HBQ1Q8A/100_`
Wallet should support this link: `https://wallet.nimiq.com/#_request/NQ208P9L3YMDGQYT1TAA8D0GMC125HBQ1Q8A/100_`
and it should have the same UI as `https://wallet.nimiq.com/nimiq:NQ208P9L3YMDGQYT1TAA8D0GMC125HBQ1Q8A?amount=100`.

Is that correct?

**Comment by sisou** [comment]
@mariofriz yes, that's correct. The old link format should probably be redirected to the new format for better modularity. Then, when we close the Safe and redirect to wallet, it can process it.
