### ISSUE TITLE
Be able to add a label on a Login Files

### ISSUE THREAD

**Issue by svub** [nimiq/wallet#25]
Having a few accounts, I noticed it can get confusing because the files look the same. While it's true that changing the file name helps, it would be cool to be able to add a label to a login file - e.g. "Savings" - when creating it.

**Comment by mariofriz** [comment]
I'd be willing to look into this, any considerations to be taken into account?

**Comment by sisou** [comment]
Needs to still look fancy :smile:

**Comment by mariofriz** [comment]
Just hacked something that allows to export file with name in it.
For now it only works when user downloads file from account menu and generates a "export" request to keyguard.

I guess it should also work for create account, change password and import words.

Preview (design still needs improvement...):
<img src="https://user-images.githubusercontent.com/1634484/110124934-03c0e500-7dc3-11eb-9395-b066d5e7cddd.png" width="250"/>

**Comment by mariofriz** [comment]
@svub Can this issue be closed?

**Comment by sisou** [comment]
Resolved by https://github.com/nimiq/keyguard/pull/422.
