### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by BARUCHER777** [nimiq/wallet#29]
Hello dear developers, I have a problem with logging into my wallet .... I forgot to create a login file and a seed phrase, just recently I had to clear cookies in my browser, now I can not open my wallet, tell me what to do to restore access:?

**Comment by hst-m** [comment]
Was it not explained well enough to you during the login process, that you need to save those somewhere? How much did you lose
![Screenshot_20200804-003721_Chrome](https://user-images.githubusercontent.com/65402951/89266504-da509880-d5ea-11ea-8876-45fa3f9781db.jpg)

**Comment by sisou** [comment]
Sorry, there is nothing we can do in this case. If you have deleted your browser storage, especially in the Keyguard, all data about your key is gone. Without login file or backup it may only be recoverable by a data recovery expert, if you haven't used that computer/device much afterwards.

We believe we have added plenty of warnings about your account being not secure in the Wallet, you even get prompted to save your login file after account creation.

I hope you recover from your loss and stay around in the cryptoverse.

All the best,
Sören
