### ISSUE TITLE
stale balance on firefox/ios

### ISSUE THREAD

**Issue by ralyodio** [nimiq/wallet#40]
I recently switched to firefox on ios to de-google/apple myself.

My balances aren't updating and when I clear cache I just get a spinner.

**Comment by sisou** [comment]
I believe Firefox on iOS is not supported, as it's not a real browser. Apple does not allow other browser engines in iOS, so both Chrome and Firefox are glorified Apple webviews with reduced functionality. I believe Chrome on iOS still works for some reason, but Firefox will not.

**Comment by ralyodio** [comment]
app doesn't work in ios/safari either. been this way for two weeks now.
