### ISSUE TITLE
Feature Request: Adding a QR code in the cashlink creator

### ISSUE THREAD

**Issue by Jasseltov** [nimiq/wallet#49]
To widen the user options for givaways with cashlinks, I would suggest displaying a downloadable or copyable QR code in addition to the text link. 
In the giftcard creator a QR code is alread displayed, but integrated in the template.

Maybe a somehow combination of cashlinks and giftcards in the flow could be a benefit as well

**Comment by sisou** [comment]
Good idea to make a button to generate a QR code. In the meantime you can paste your cashlink URL into any QR code generator, like this one: https://www.qr-code-generator.com/
