### ISSUE TITLE
Apple Pay for buying NIM

### ISSUE THREAD

**Issue by code3z** [nimiq/wallet#64]
While simplex provides Apple Pay, it has high fees. It would be great if buying NIM was as easy as buying an app.

**Comment by sisou** [comment]
Buying NIM in the Wallet with OASIS has one important requirement for the EUR transaction type: it must be **irreversible**.

The swap in the wallet is a so-called _atomic swap_ that works between two HTLC "smart" contracts. During the swap, possession of the assets is irreversibly swapped between the two swap sides. Using a EUR payment method that allows to revert EUR payments would enable rampant fraud and us losing all our money. This excludes everything that is using a Credit Card under the hood, so excludes Google/Apple Pay, Paypal, etc.
