### ISSUE TITLE
(PWA) iOS status bar

### ISSUE THREAD

**Issue by felix-schindler** [nimiq/wallet#69]
# Description
On iOS the status bar / icons are either black on black or white on white (depending on dark or light mode).

## Preview
`iPhone Xs, iOS 15.2`
<details>
    <summary>Light mode</summary>
    <img src="https://user-images.githubusercontent.com/65357346/147682597-c3d71a07-8665-4aeb-a8b8-a124e74a9224.jpeg" alt="iOS status bar light mode">
</details>
<details>
    <summary>Dark mode</summary>
    <img src="https://user-images.githubusercontent.com/65357346/147682600-e3f879af-850d-4408-90c7-3c53634ca046.jpeg" alt="iOS status bar dark mode">
</details>

## Reason
The "default" value of this meta tag causes this issue. (I'm not sure why, it's just Apple.)
```html
<meta name="apple-mobile-web-app-status-bar-style" content="default">
```

# Solution
With improved support of the "theme-color" meta tag in Safari 15 it would make sense to make use of this feature and setting a theme color. Since the status bar background color get's set to the theme color and the foreground color (white/black) is being calculated automatically, the error would not occur anymore.

```html
<meta name="theme-color" content="#DBDCE2">
```

File link:
https://github.com/nimiq/wallet/blob/5a5f59013e3489faa4bb46dc19d22526fb0f2366/vue.config.js#L139

Replace with:
```javascript
themeColor: '#DBDCE2'
```

## Another solution
It would also be possible to change the status bar style meta tag value to "black-translucent" and add a fixed dark header with env-padding which would be much more complicated.
```html
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

### Related articles
[iOS 14.5 "Status bar change"](https://firt.dev/ios-14.5/#status-bar-change)
[Safari 15 "Theme color"](https://useyourloaf.com/blog/safari-15-theme-color/)
["The Notch" and CSS](https://css-tricks.com/the-notch-and-css/)

**Comment by sisou** [comment]
Awesome, thanks for the thorough report!

I think the gray you suggest is a bit dark? Especially as in non-full-screen mode it would also color the whole top bar (on Android and also now on iOS(?)), which might look sad? So my suggestion would be to use the dark Nimiq Blue `#1f2348` or using `white`, but white would probably be bad for dark-theme users?

**Comment by felix-schindler** [comment]
Yes, it would now also color the whole top bar on iOS.
I personally think since Nimiq Wallet does not have a dark-theme (yet? #8) it doesn't matter.

To respect dark theme it would be possible setting the theme color something like this:
But I'd guess it would have to be set manually rather than with the vue config.
```html
<meta name="theme-color" content="#white" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#1f2348" media="(prefers-color-scheme: dark)">
```
