### ISSUE TITLE
Update notification - Environment Padding

### ISSUE THREAD

**Issue by felix-schindler** [nimiq/wallet#92]
Due to the navigation bar it's hard to press the update button of the [UpdateNotification](https://github.com/nimiq/wallet/blob/master/src/components/UpdateNotification.vue#L58) on devices like the iPhone.

Just like the MobileActionBar there should be a `padding-bottom` including the env-padding.
https://github.com/nimiq/wallet/blob/0fd0d6b05f3c97c55384917718379b2c83eb4a92/src/components/MobileActionBar.vue#L97

<br>

> [CSS and the Notch](https://css-tricks.com/the-notch-and-css/)

**Comment by sisou** [comment]
Oh, good catch, thank you! 👍

**Comment by sisou** [comment]
I'm waiting for one other fix to be approved and merged (#91), then this will get deployed early next week!
