### ISSUE TITLE
 scroll mask overflows in address list

### ISSUE THREAD

**Issue by onmax** [nimiq/wallet#93]
**Reported by**: _Community member in a Telegram group_
**Browsers**: Brave Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit). Probably this bug also occurs in other browsers.

## Description
Overflow with 'scroll-mask top' & 'scroll-mask bottom' when screen width is between 2000px-2070px

## Example
![image](https://user-images.githubusercontent.com/22072217/156215969-629f3e18-b587-49b7-8c77-9713a7394a55.png)

**Comment by sisou** [comment]
Resolved by #94.
